-- UNION
-- 서로 다른 두 개 이상의 SELECT 문 결과물을 위아래로 길게 이어 붙일 때
-- 두 테이블의 컬럼 구성이 같아야 하며, 각 SELECT 문 사이에 UNION 키워드를 넣음
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
    OR DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL # 중복 없다고 조건에 명시됨

SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
    OR DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
    
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC