-- 같은 테이블을 여러번 JOIN시키기
SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO PARENT
JOIN ITEM_TREE TREE ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
JOIN ITEM_INFO CHILD ON TREE.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY CHILD.ITEM_ID DESC