-- 이름이 다르지만 내용이 동일한 열(식당 ID)을 JOIN시키기 : ON
-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
-- 평균 점수 계산; 소수점 세번째 반올림 -> AVG, ROUND
SELECT
    INFO.REST_ID,
    INFO.REST_NAME,
    INFO.FOOD_TYPE,
    INFO.FAVORITES,
    INFO.ADDRESS,
    ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO INFO 
JOIN REST_REVIEW REVIEW ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE '서울%'
GROUP BY 
    INFO.REST_ID,
    INFO.REST_NAME,
    INFO.FOOD_TYPE,
    INFO.FAVORITES,
    INFO.ADDRESS
ORDER BY SCORE DESC, INFO.FAVORITES DESC