-- 코드를 입력하세요
SELECT 
    BOARD.TITLE,
    BOARD.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    REPLY.CREATED_DATE
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_REPLY REPLY USING (BOARD_ID)
-- DATEFORMAT 사용
WHERE DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
-- 복수의 colum join: using 사용
-- 이 문제의 경우 WRITER_ID, CONTENTS, CREATED_DATA가 중복이지만 다른 의미
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC